---
links:
  - title: Workplace Gamification
    url: "/workplace-gamification/"
    desc: Improve workplace culture and staff motivation with 60-day gamification pilot

  - title: Gamification Consultation
    url: "/gamification-consultation/"
    desc: Reach out to get my advice on your gamification project

  - title: Engagement Strategy
    url: "/engagement-strategy/"
    desc: Ask me to help you built a complete user engagement & loyalty strategy.

  - title: LinkedIn profile
    target: _blank
    url: "https://www.linkedin.com/in/dariusztarczynski/"
    desc: Find my LinkedIn profile with new posts about gamification

